### ISSUE TITLE
test-Thierry failure on i386 architecture

### ISSUE THREAD

**Issue by jgmbenoit** [Normaliz/Normaliz#156] opened 2017-11-06 04:34 UTC
It appears that one test currently fails on i386 arch (aka 32bit arch) in unstable Debian environment: the faulty test is [test-minus-Thierry](https://github.com/Normaliz/Normaliz/files/1445017/normaliz-3_4_0-i389-test-minus-Thierry_diff.txt).  This is likely related to the [Debian Bug #877210](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877210).

**Comment by w-bruns** [comment] 2017-11-06 17:37
Most likely the failure on 32 bit architecture is caused by a bug that was already discovered on MS Windows. It happens when long and long long don't have the same bit size. See https://github.com/Normaliz/Normaliz/releases.

I have no real explanation for the other bug observed with version 3.1.1. It is possible that it was caused by an unitialized variable. I vaguely remember such a problem in the input routine found about a year ago.

Before packaging 3.4.0, the long vs. long long bug and the other more serious bug (also described on https://github.com/Normaliz/Normaliz/releases)should be removed. I can make a version 3.4.1 that is identical to 3.4.0 except for bug fixes. On the other hand, I plan to post 3.5.0 before Christmas.

**Comment by jgmbenoit** [comment] 2017-11-07 04:28
The bug report deals with version 3.4.0. If you think that the mentioned version 3.4.1 will fix this issue, please proceed. BTW, have you try to reproduce the issue ?

**Comment by jgmbenoit** [comment] 2017-11-09 03:32
Have you made any progress ?

**Comment by w-bruns** [comment] 2017-11-09 10:41
I am on a trip this week. Next week I hope I will have an opportunioty to reproduce the error with a 32 bit version, although I am convinced it is the known long vs ling long problem. Then there are two alternatives:
(i) I make a bugfix version 3.4.1 next week,
(ii) I make a version with bigfixes and new features by the end of November.
I will make (ii) anyway.. So let me know if you want (i). It is not a big deal.

**Comment by jgmbenoit** [comment] 2017-11-09 11:17
I suspect something related to integer representation as well. But I am not familiar enough with the code to step forward. Given that, having (i) will allow me to finalize my package (and to discard the AUTORM tag on it and on packages which depend on it).

**Comment by jgmbenoit** [comment] 2017-11-09 11:18
In short, I want (i).

**Comment by w-bruns** [comment] 2017-11-13 12:43
(i) has been done. I have published the release 3.4.1 with the bug fixes for 3.4.0.
I have compiled a 32 bit version, and it has passed all tests.

**Comment by jgmbenoit** [comment] 2017-11-13 15:21
Thanks a lot. I will package it next Friday.

**Comment by w-bruns** [comment] 2017-11-13 16:39
I assume that you run your tests first.

**Comment by jgmbenoit** [comment] 2017-11-14 04:30
Basic tests before uploading, then the Debian robots perform a myriad of tests. If one fails, I will react accordingly. Nothing new here.

**Comment by jgmbenoit** [comment] 2017-11-15 13:49
It appears that the test test-/5x5PF.diff fails on some architectures.

**Comment by w-bruns** [comment] 2017-11-15 14:30
That is a separate issue. I close this one, since the 32bit problem has been solved.

**Closed by w-bruns** 2017-11-15 14:30 UTC
